services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    # Define this in .env 
    hostname: ${NETDATA_HOSTNAME}
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor=unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /:/host:ro,rslave
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /run/dbus:/run/dbus:ro

    restart: unless-stopped

    environment:
      - NETDATA_CLAIM_URL=https://app.netdata.cloud
    env_file:
      # Define NETDATA_CLAIM_TOKEN and NETDATA_CLAIM_ROOMS in the following:
      - secrets/netdata.env

    networks:
      default:
      inverseproxy_shared:

    labels:
      traefik.enable: "true"
      traefik.http.routers.netdata-secure.rule: Host(`${NETDATA_HOSTNAME}`)
      traefik.http.routers.netdata-secure.entrypoints: web-main
      traefik.http.routers.netdata-secure.tls: "true"
      traefik.http.routers.netdata-secure.tls.certResolver: letsencrypt
      traefik.http.routers.netdata-secure.service: netdata-svc
      traefik.http.services.netdata-svc.loadbalancer.server.port: 19999

      #basicauth
      traefik.http.middlewares.netdata-auth.basicAuth.usersFile: "/etc/traefik/secrets/netdata-users"
      traefik.http.routers.netdata-secure.middlewares: netdata-auth

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:

networks:
  default:
    driver_opts:
      encrypted: 1
  inverseproxy_shared:
    external: true
